# Generated by Django 4.2.1 on 2023-07-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JardinVecino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cotraseña',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(db_column='idTipo', default=1, on_delete=django.db.models.deletion.CASCADE, to='JardinVecino.tipousuario'),
        ),
    ]
